print("Hacking Facebook ID.....")
print("Processing.......")
print("Starting Attacking............")
print("Hacking ID 0%")
print("Hacking ID 20%")
print("Hacking ID 40%")
print("Hacking ID 60%")
print("Hacking ID 80%")
print("Hacking ID 100%")
print("ID Hacked Sucessfully")