print("Hacking NASA.....")
print("Processing.......")
print("Starting Attacking")
print("Hacking NASA 0%")
print("Hacking NASA 20%")
print("Hacking NASA 40%")
print("Hacking NASA 60%")
print("Hacking NASA 80%")
print("Hacking NASA 100%")
print("NASA Hacked Sucessfully")